// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DelogueAssignment.Entities;

public partial class Note
{
    public int NoteId { get; set; }

    public int TaskId { get; set; }

    public int AuthorId { get; set; }

    public string Content { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User Author { get; set; }

    public virtual Task Task { get; set; }
}