// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DelogueAssignment.Entities;

public partial class Task
{
    public int TaskId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateOnly CreatedAt { get; set; }

    public virtual ICollection<Note> Notes { get; set; } = new List<Note>();
}